SELECT ?id ?name ?birthDate ?calendarModel ?precision ?siteLinks WHERE {
   ?id wdt:P31 wd:Q5 .
   ?id p:P569/psv:P569 ?birthDateNode .
   ?id rdfs:label ?name .
   ?id wikibase:sitelinks ?siteLinks .
   ?birthDateNode wikibase:timePrecision ?precision .
   ?birthDateNode wikibase:timeValue ?birthDate . 
   ?birthDateNode wikibase:timeCalendarModel ?calendarModel .
   FILTER (1875 <= year(?birthDate) && year(?birthDate) < 1900) .
   FILTER (?precision >= 11) .
   FILTER (?siteLinks > 30) .
   FILTER (LANG(?name) = "en") .
   SERVICE wikibase:label {
      bd:serviceParam wikibase:language "en" .
   }
}
ORDER BY desc(?siteLinks)